### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by fraknoiadam** [fraknoiadam/bootstrap-stopwatch#1]
- [ ] Mergelni a jelenlegi két branchet
- [ ] Jelenleg 1 mp-vel kevesebb idő áll rendelkezésre a versenyen.
- [ ] 0:00:00-nál még mindig megy az óra, amit észreveszek, ha hozzáadok +1 órát. Erre jó lenne egy beállítás
- [ ] Jó lenne ha cookie-ban le tudná tárolni az időt.
- [ ] Egy online szerverről is lekérdezhetné az adatokat és akkor lehetne szinkronizálni különböző órákat.
- [ ] ha a másodperc 11, akkor szétcsúszik az óra.
- [ ] Szöveget és beágyazást lehetne a beállításokban állítani .
- [ ] Jó lenne ha kézzel is be lehetne állítani az óra pozícióját, méretét, szövegek pozícióját, méretét, stb.
- [ ] Bal felső sarkoba kattintva előjöjjön a beállítások menü.
- [ ] Átnevezni a projektet timer-for-competitions-re.
- [ ] Space-el is el lehessen indítani/megállítani a timert.
- [ ] Legyen egy főoldal, ahol egyszerűen be lehet állítani a dolgokat (mint pl. crab.fit)
- [ ] Legyen preview, hogy hogyan fog kinézni az óra és lehessen görgetni az időnél.
